force-app/main/default/objects/Weather_History__c/Weather_History__c.object-meta.xml
<CustomObject>
    <description>Stores weather history data of a location</description>
    <label>Weather History</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Weather History</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather_History__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MIN_TEMPERATURE</fullName>
                <label>Minimum Temperature</label>
            </value>
            <value>
                <fullName>MAX_TEMPERATURE</fullName>
                <label>Maximum Temperature</label>
            </value>
            <value>
                <fullName>AVG_TEMPERATURE</fullName>
                <label>Average Temperature</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Weather_History__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/weather/jobs/WeatherDataCleanupSchedule.cls
public with sharing class WeatherDataCleanupSchedule implements Schedulable {

    public static final String CRON = '00 55 23 * * ?';
    private static final String LOCATION = 'Lucknow, UP, India';
    private static final Date TODAY = Date.today();

    public void execute(SchedulableContext sc) {
        saveMinMaxAvgTemperatures();
        WeatherDataCleanupBatch batch = new WeatherDataCleanupBatch();
        Database.executeBatch(batch, 2000);
    }


    private void saveMinMaxAvgTemperatures() {
        Weather_History__c maxTemperature = WeatherHistoryRepository.getMaxTemperatureByLocationForDate(LOCATION, TODAY);
        Weather_History__c minTemperature = WeatherHistoryRepository.getMinTemperatureByLocationForDate(LOCATION, TODAY);
        maxTemperature.Data_Type__c = WeatherHistoryRepository.DATA_TYPE_MAX_TEMPERATURE;
        minTemperature.Data_Type__c = WeatherHistoryRepository.DATA_TYPE_MIN_TEMPERATURE;

        Weather_History__c avgTemperature = new Weather_History__c();
        avgTemperature.Location__c = maxTemperature.Location__c;
        avgTemperature.Temperature__c = WeatherHistoryRepository.getAvgTemperatureByLocationForDate(location, TODAY);
        avgTemperature.Data_Type__c = WeatherHistoryRepository.DATA_TYPE_AVG_TEMPERATURE;

        WeatherHistoryRepository.insertWeatherHistory(avgTemperature);
        WeatherHistoryRepository.updateWeatherHistory(maxTemperature);
        WeatherHistoryRepository.updateWeatherHistory(minTemperature);
    }
}