force-app/main/default/objects/Weather_History__c/Weather_History__c.object-meta.xml
<CustomObject>
    <description>Stores weather history data of a location</description>
    <label>Weather History</label>
    <nameField>
        <displayFormat>W-{0000}</displayFormat>
        <label>Weather History</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Weather_History__c/fields/Temperature__c.field-meta.xml
<CustomField>
    <fullName>Temperature__c</fullName>
    <label>Temperature</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/weather/jobs/WeatherAPIFutureCaller.cls
public with sharing class WeatherAPIFutureCaller {
    @Future(Callout = true)
    public static void calloutAPI() {
        WeatherAPI api = new WeatherAPI();
        api.setLocation('Lucknow').submitWeatherAPIRequest().populateData();
        Weather_History__c history = new Weather_History__c();
        history.Location__c = api.resolvedAddress;
        history.Temperature__c = api.currentTemperature;
        history.Timestamp__c = DateTime.now();
        WeatherHistoryRepository.insertWeatherHistory(history);
    }
}