force-app/main/default/objects/Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Represents a single person in contact tracing application.</description>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Health_Status__c.field-meta.xml
<CustomField>
    <fullName>Health_Status__c</fullName>
    <description>Represent heath status of a person.</description>
    <label>Health Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/contact-tracing/trigger-handlers/CTLocationTriggerHandler.cls
public with sharing class CTLocationTriggerHandler {
    public static void beforeInsert(List<Location__c> newRecords) {
        for (Location__c location : newRecords) {
            location.Status__c = 'Green';
            location.Status_Update_Date__c = Date.today();
        }
    }

    public static void beforeUpdate(Map<Id, Location__c> oldMap, List<Location__c> newRecords) {
        for (Location__c location : newRecords) {
            String oldStatus = oldMap.get(location.Id).Status__c;
            String newStatus = location.Status__c;
            if (oldStatus != newStatus) {
                location.Status_Update_Date__c = Date.today();
            }
        }
    }

    public static void afterUpdate(Map<Id, Location__c> oldMap, List<Location__c> newRecords) {
        Set<Id> redStatus = new Set<Id>();

        for (Location__c location : newRecords) {
            String oldStatus = oldMap.get(location.Id).Status__c;
            String newStatus = location.Status__c;
            if (oldStatus != newStatus) {
                redStatus.add(location.Id);
            }
        }

        List<Location_Tracing__c> locationTraces = CTLocationTracingController.getLocationsByLocationIds(redStatus);
        Set<Id> personIds = new Set<Id>();

        for (Location_Tracing__c trace : locationTraces) {
            personIds.add(trace.Person__c);
        }

        List<Person__c> peopleToUpdate = new List<Person__c>();
        for (Id pid : personIds) {
            peopleToUpdate.add(new Person__c(Id = pid, Health_Status__c = 'Yellow'));
        }

        if (peopleToUpdate.size() > 0) {
            update as user peopleToUpdate;
        }
    }
}