force-app/main/default/objects/Person__c/Person__c.object-meta.xml
<CustomObject>
    <description>Represents a single person in contact tracing application.</description>
    <label>Person</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Persons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Person__c/fields/Health_Status__c.field-meta.xml
<CustomField>
    <fullName>Health_Status__c</fullName>
    <description>Represent heath status of a person.</description>
    <label>Health Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/contact-tracing/jobs/CTUpdatePersonStatusBatch.cls
public with sharing class CTUpdatePersonStatusBatch implements Database.Batchable<SObject> {
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date fourteenDaysAgo = Date.today().addDays(-14);
        List<String> healthStatuses = new List<String>{ 'Red', 'Orange', 'Yellow' };
        return Database.getQueryLocator(
            'SELECT Id, Health_Status__c FROM Person__c WHERE Status_Update_Date__c = :fourteenDaysAgo AND Health_Status__c IN :healthStatuses'
        );
    }

    public void execute(Database.BatchableContext bc, List<Person__c> scope) {
        for (Person__c person : scope) {
            person.Health_Status__c = 'Green';
        }

        update as user scope;
    }

    public void finish(Database.BatchableContext bc) {
        System.debug('CTUpdatePersonStatusBatch Complete.');
    }
}